#!/bin/bash
#!usr/bin/env bash

# Script: Ops 201 Class 04 Ops Challenge Solution
# Author: Justin R. Dotson
# Date of latest revision: 02-09-23
# Purpose: Write a script that:
# Creates four directories: dir1, dir2, dir3, dir4
# Put the **names** of the four directories in an array
# References the array variable to create a new .txt file in each directory

# Referenced : https://phoenixnap.com/kb/list-processes-linux
# Referenced : https://www.linode.com/docs/guides/use-the-ps-aux-command-in-linux/
# Referenced : https://www.hostinger.com/tutorials/vps/how-to-manage-processes-in-linux-using-command-line
# Referenced : https://www.freecodecamp.org/news/linux-list-processes-how-to-check-running-processes/

# Main



# set condition
kcommand="no"
# While conditional Loop
while [[ $kcommand == "no" ]] # => True
do 

ps x # Display previuosly running processes
echo "Here are previously running processes,be careful what you choose."
echo "Choose a process to stop; type a PID #:"
read kill_process
echo "You chose:" $kill_process
echo "Is this correct? yes/no"
read kcommand
done

kill -9 $kill_process