#!/bin/bash
#!usr/bin/env bash

# Script: Ops 201 Class 04 Ops Challenge Solution
# Author: Justin R. Dotson
# Date of latest revision: 02-09-23
# Purpose: Write a script that:
# Creates four directories: dir1, dir2, dir3, dir4
# Put the **names** of the four directories in an array
# References the array variable to create a new .txt file in each directory

# Referenced : https://phoenixnap.com/kb/list-processes-linux
# Referenced :

# 

# Main


# ps  Display running processes
# echo "Here are currently running processes,"
#echo "Choose a process to stop; type a PID #:"
#read kill_process
#echo "You chose:" $kill_process

# While conditional Loop

# set condition
kcommand="no"

while [[ $kcommand == "no" ]] # => True
do 

ps # Display running processes
echo "Here are currently running processes,"
echo "Choose a process to stop; type a PID #:"
read kill_process
echo "You chose:" $kill_process
echo "Is this correct? yes/no"
read kcommand
done

kill -9 $kill_process